// Catálogo de nomes de mercado (id 'slug:subId' → nome PT).
// Espelho do CreateMarkets do arbbetting_master (markets-futebol.interface.ts).
// Gerado a partir do catálogo; fonte da verdade dos ids é o arbbetting.
export const MARKET_NAMES: Record<string, string> = {
  'match-winner:1': 'Resultado Final',
  'match-winner-pa:1': 'Resultado Final PA',
  'duplo-green:1': 'Duplo Green',
  'match-winner-so:1': 'Resultado Final SO',
  'match-winner-lay:2': 'Resultado Final Lay',
  'match-winner-1st-half:3': 'Resultado Final - 1º Tempo',
  'match-winner-2nd-half:4': 'Resultado Final - 2º Tempo',
  'total-goals-over-under:5': 'Total de Gols Mais/Menos',
  'total-goals-over-under-1st-half:6': 'Total de Gols Mais/Menos - 1º Tempo',
  'total-goals-over-under-2nd-half:7': 'Total de Gols Mais/Menos - 2º Tempo',
  'both-teams-to-score:8': 'Ambas equipes Marcam',
  'total-cards-over-under:9': 'Total de Cartões Acima/Abaixo',
  'yellow-cards-result:8999': 'Cartões Amarelos Resultado',
  'cards-result:9000': 'Cartões Resultado',
  'total-yellow-cards-over-under:9001': 'Total de Cartões Amarelo Acima/Abaixo',
  'total-yellow-cards-home-over-under:9002': 'Cartões Amarelo Casa Mais/Menos',
  'total-yellow-cards-away-over-under:9003': 'Cartões Amarelo Fora Mais/Menos',
  'yellow-cards-handicap:9004': 'HP Cartões Amarelo',
  'total-corners-over-under:10': 'Escanteios Mais/Menos',
  'total-corners-over-under-1st-half:1000': 'Escanteios Mais/Menos - 1HT',
  'total-corners-over-under-2nd-half:1001': 'Escanteios Mais/Menos - 2HT',
  'total-corners-home-over-under:1002': 'Escanteios Total - Casa',
  'total-corners-home-over-under-1st-half:1004': 'Escanteios Total - Casa - 1HT',
  'total-corners-away-over-under:1003': 'Escanteios Total - Fora',
  'total-corners-away-over-under-1st-half:1005': 'Escanteios Total - Fora - 1HT',
  'double-chance:11': 'Chance Dupla',
  'double-chance-1st-half:12': 'Chance Dupla - 1º Tempo',
  'double-chance-2nd-half:13': 'Chance Dupla - 2º Tempo',
  'asian-handicap:14': 'Handicap',
  'draw-no-bet:15': 'Empate Anula',
  'european-handicap:16': 'Handicap Europeu',
  'asian-handicap:17': 'Handicap Asiático',
  'goal-line-handicap:18': 'Handicap Gols Linhas',
  'to-qualify:19': 'Classificar-se',
  'shots-on-goal-winner:20': 'Chutes no Gol Ganhador',
  'shots-on-goal-over-under:2001': 'Chutes no Gol Acima/Abaixo',
  'shots-on-goal-handicap:2002': 'Chutes no Gol Handicap',
  'shots-over-under:2005': 'Chutes Total',
  'shots-home-over-under:2006': 'Chutes Total: Casa',
  'shots-away-over-under:2007': 'Chutes Total: Fora',
  'shots-on-goal-home-over-under:21': 'Chutes ao Gol: Casa',
  'shots-on-goal-away-over-under:22': 'Chutes ao Gol: Fora',
  'offsides-result:41': 'Impedimentos Resultado',
  'offsides-over-under:42': 'Total Impedimentos',
  'offsides-home-over-under:43': 'Impedimentos: Casa',
  'offsides-away-over-under:44': 'Impedimentos: Fora',
  'total-goals-home-over-under:3000': 'Gols Casa Mais/Menos',
  'total-goals-away-over-under:3001': 'Gols Fora Mais/Menos',
  'total-goals-home-over-under-1st-half:3002': 'Gols Casa Mais/Menos - 1º Tempo',
  'total-goals-away-over-under-1st-half:3003': 'Gols Fora Mais/Menos - 1º Tempo',
  'total-goals-home-over-under-2nd-half:3004': 'Gols Casa Mais/Menos - 2º Tempo',
  'total-goals-away-over-under-2nd-half:3005': 'Gols Fora Mais/Menos - 2º Tempo',
  'total-goals-odd-even:3006': 'Total de Gols Ímpar/Par',
  'total-goals-odd-even-1st-half:3007': 'Total de Gols Ímpar/Par - 1º Tempo',
  'both-teams-to-score-1st-half:3008': 'Ambas Marcam - 1º Tempo',
  'both-teams-to-score-2nd-half:3009': 'Ambas Marcam - 2º Tempo',
  'draw-no-bet-1st-half:3010': 'Empate Anula - 1º Tempo',
  'draw-no-bet-2nd-half:3011': 'Empate Anula - 2º Tempo',
  'asian-handicap-1st-half:3012': 'Handicap Asiático - 1º Tempo',
  'asian-handicap-2nd-half:3013': 'Handicap Asiático - 2º Tempo',
  'european-handicap-1st-half:3014': 'Handicap Europeu - 1º Tempo',
  'european-handicap-2nd-half:3015': 'Handicap Europeu - 2º Tempo',
  'exact-goals:3040': 'Número Exato de Gols',
  'exact-goals-home:3041': 'Gols Exatos - Casa',
  'exact-goals-away:3042': 'Gols Exatos - Fora',
  'goals-band:3043': 'Faixa de Total de Gols',
  'half-time-full-time:3044': 'Intervalo/Final',
  'correct-score:3045': 'Resultado Correto',
  'result-and-btts:3046': 'Resultado & Ambas Marcam',
  'result-and-total-goals:3047': 'Resultado & Total de Gols',
  'double-chance-and-btts:3048': 'Dupla Chance & Ambas Marcam',
  'btts-both-halves:3049': 'Ambas Marcam nos 2 Tempos',
  'first-goal:3051': '1º Gol (Casa/Nenhum/Fora)',
  'half-with-most-goals:3052': 'Tempo com Mais Gols',
  'btts-and-total-goals:3053': 'Ambas Marcam & Total de Gols',
  'corners-result:3100': 'Escanteios Resultado (Equipe com mais)',
  'corners-result-1st-half:3101': 'Escanteios Resultado - 1º Tempo',
  'corners-handicap:3102': 'Handicap Escanteios (Asiático)',
  'corners-handicap-1st-half:3103': 'Handicap Escanteios - 1º Tempo',
  'corners-european-handicap:3104': 'Handicap Europeu Escanteios',
  'corners-odd-even:3105': 'Escanteios Ímpar/Par',
  'corners-odd-even-1st-half:3106': 'Escanteios Ímpar/Par - 1º Tempo',
  'total-corners-home-over-under-2nd-half:3107': 'Escanteios Casa Mais/Menos - 2º Tempo',
  'total-corners-away-over-under-2nd-half:3108': 'Escanteios Fora Mais/Menos - 2º Tempo',
  'total-corners-away-over-under-1st-half:3109': 'Escanteios Fora Mais/Menos - 1º Tempo',
  'total-cards-home-over-under:3200': 'Cartões Casa Mais/Menos (Total)',
  'total-cards-away-over-under:3201': 'Cartões Fora Mais/Menos (Total)',
  'total-cards-over-under-1st-half:3202': 'Total de Cartões Mais/Menos - 1º Tempo',
  'total-cards-home-over-under-1st-half:3203': 'Cartões Casa Mais/Menos - 1º Tempo',
  'total-cards-away-over-under-1st-half:3204': 'Cartões Fora Mais/Menos - 1º Tempo',
  'total-cards-home-over-under-2nd-half:3205': 'Cartões Casa Mais/Menos - 2º Tempo',
  'total-cards-away-over-under-2nd-half:3206': 'Cartões Fora Mais/Menos - 2º Tempo',
  'cards-handicap:3207': 'Handicap Cartões (Total)',
  'cards-result-1st-half:3208': 'Cartões Resultado - 1º Tempo',
  'cards-draw-no-bet:3209': 'Empate Anula Cartões',
  'total-red-cards-over-under:3210': 'Total de Cartões Vermelhos Mais/Menos',
  'shots-result:3300': 'Finalizações Resultado (Equipe com mais)',
  'shots-result-1st-half:3301': 'Finalizações Resultado - 1º Tempo',
  'shots-handicap:3302': 'Handicap Finalizações',
  'shots-handicap-1st-half:3303': 'Handicap Finalizações - 1º Tempo',
  'shots-over-under-1st-half:3304': 'Finalizações Mais/Menos - 1º Tempo',
  'shots-home-over-under-1st-half:3305': 'Finalizações Casa Mais/Menos - 1º Tempo',
  'shots-away-over-under-1st-half:3306': 'Finalizações Fora Mais/Menos - 1º Tempo',
  'shots-on-goal-result:3307': 'Chutes no Gol Resultado',
  'shots-on-goal-over-under-1st-half:3308': 'Chutes no Gol Mais/Menos - 1º Tempo',
  'shots-on-goal-home-over-under-1st-half:3309': 'Chutes no Gol Casa Mais/Menos - 1º Tempo',
  'shots-on-goal-handicap-1st-half:3310': 'Handicap Chutes no Gol - 1º Tempo',
  'offsides-handicap:3400': 'Handicap Impedimentos',
  'offsides-over-under-1st-half:3401': 'Impedimentos Mais/Menos - 1º Tempo',
  'offsides-home-over-under-1st-half:3402': 'Impedimentos Casa Mais/Menos - 1º Tempo',
  'offsides-away-over-under-1st-half:3403': 'Impedimentos Fora Mais/Menos - 1º Tempo',
  'total-fouls-over-under:3500': 'Total de Faltas Mais/Menos',
  'total-fouls-home-over-under:3501': 'Faltas Casa Mais/Menos',
  'total-fouls-away-over-under:3502': 'Faltas Fora Mais/Menos',
  'total-fouls-over-under-1st-half:3503': 'Total de Faltas Mais/Menos - 1º Tempo',
  'total-fouls-home-over-under-1st-half:3504': 'Faltas Casa Mais/Menos - 1º Tempo',
  'total-fouls-away-over-under-1st-half:3505': 'Faltas Fora Mais/Menos - 1º Tempo',
  'total-tackles-over-under:3600': 'Total de Desarmes Mais/Menos',
  'total-tackles-home-over-under:3601': 'Desarmes Casa Mais/Menos',
  'total-tackles-away-over-under:3602': 'Desarmes Fora Mais/Menos',
  'total-tackles-over-under-1st-half:3603': 'Total de Desarmes Mais/Menos - 1º Tempo',
  'total-throwins-over-under:3700': 'Total de Laterais Mais/Menos',
  'total-throwins-home-over-under:3701': 'Laterais Casa Mais/Menos',
  'total-throwins-away-over-under:3702': 'Laterais Fora Mais/Menos',
  'total-throwins-over-under-1st-half:3703': 'Total de Laterais Mais/Menos - 1º Tempo',
  'total-goalkicks-over-under:3800': 'Total de Tiros de Meta Mais/Menos',
  'total-goalkicks-home-over-under:3801': 'Tiros de Meta Casa Mais/Menos',
  'total-goalkicks-away-over-under:3802': 'Tiros de Meta Fora Mais/Menos',
  'goalkicks-handicap:3803': 'Handicap Tiros de Meta',
  'total-goalkicks-over-under-1st-half:3804': 'Total de Tiros de Meta Mais/Menos - 1º Tempo',
  // Vence a Zero (win-to-nil): a equipe vence E não sofre gols. Mercado Sim/Não.
  'win-to-nil-home:3906': 'Casa Vence a Zero',
  'win-to-nil-away:3907': 'Fora Vence a Zero',
  'win-to-nil-home-1st-half:3908': 'Casa Vence a Zero - 1º Tempo',
  'win-to-nil-away-1st-half:3909': 'Fora Vence a Zero - 1º Tempo',
};

// Mapa auxiliar por slug (1ª ocorrência) para fallback quando vier sem subId.
export const MARKET_NAMES_BY_SLUG: Record<string, string> = Object.entries(MARKET_NAMES).reduce(
  (acc, [key, name]) => { const slug = key.split(':')[0]; if (!acc[slug]) acc[slug] = name; return acc; },
  {} as Record<string, string>
);
